In [2]:
import pandas as pd 
ap_data=pd.read_csv("../data/appl_day5_behavioral_analysis.csv",index_col='Date',parse_dates=True)
ap_data.head()

,Close,High,Low,Open,Volume,Returns,Rolling Mean,Rolling Volatility,Cumulative Return,Fear_Greed,Risk_Adjustment_Returns,Fear_Signal,Investor_Bias,Recommendataion,sharpe_Rato,Rolling_Sharpe,Performance
Date,,,,,,,,,,,,,,,,,
2019-02-14,40.736500,40.846210,40.397824,40.476531,87342800,0.003643,37.934863,NaN,1.003643,Greed,NaN,Greed,Neutral,Hold,NaN,NaN,Poor
2019-02-15,40.645874,40.951159,40.486077,40.843833,98507200,-0.002225,38.164123,NaN,1.001410,Greed,NaN,Greed,Neutral,Hold,NaN,NaN,Poor
2019-02-19,40.767506,40.889145,40.424063,40.476534,75891200,0.002992,38.349386,NaN,1.004407,Greed,NaN,Greed,Neutral,Hold,NaN,NaN,Poor
2019-02-20,41.029861,41.337534,40.781819,40.829519,104457600,0.006435,38.546007,NaN,1.010871,Greed,NaN,Greed,Neutral,Hold,NaN,NaN,Poor
2019-02-21,40.798512,41.110951,40.617250,40.975006,68998800,-0.005639,38.712592,NaN,1.005171,Greed,NaN,Greed,Neutral,Hold,NaN,NaN,Poor

In [3]:
ap_data.columns

Index(['Close', 'High', 'Low', 'Open', 'Volume', 'Returns', 'Rolling Mean',
       'Rolling Volatility', 'Cumulative Return', 'Fear_Greed',
       'Risk_Adjustment_Returns', 'Fear_Signal', 'Investor_Bias',
       'Recommendataion', 'sharpe_Rato', 'Rolling_Sharpe', 'Performance'],
      dtype='object')

In [6]:
ap_data['Recommendataion'].value_counts()

Recommendataion
Hold    1201
Buy      279
Name: count, dtype: int64

In [7]:
def recommand(x):
    if x['Investor_Bias'] == 'Fear' and x['Performance'] == 'Good' :
        return 'Buy'
    elif x['Investor_Bias'] == 'Greed' and x['Performance'] == 'Poor' :
        return 'Sell'
    else : 
        return 'Hold'
    
ap_data['Recommendation']=ap_data.apply(recommand,axis=1)
ap_data[['Investor_Bias','Performance','Recommendation']].head(10)

           Investor_Bias Performance Recommendation
Date
2019-02-14       Neutral        Poor           Hold
2019-02-15       Neutral        Poor           Hold
2019-02-19       Neutral        Poor           Hold
2019-02-20       Neutral        Poor           Hold
2019-02-21       Neutral        Poor           Hold
2019-02-22       Neutral        Poor           Hold
2019-02-25       Neutral        Poor           Hold
2019-02-26       Neutral        Poor           Hold
2019-02-27       Neutral        Poor           Hold
2019-02-28       Neutral        Poor           Hold

In [10]:
ap_data['Recommendation'].value_counts()

Recommendation
Hold    1244
Buy      128
Sell     108
Name: count, dtype: int64

In [15]:
import plotly.graph_objects as go
fig=go.Figure()
fig.add_trace(go.Scatter(
    x=ap_data.index,
    y=ap_data['Close'],
    mode='lines',
    name='Price'
))

buy_data=ap_data[ap_data['Recommendation']== 'Hold']

fig.add_trace(go.Scatter(
    x=buy_data.index,
    y=buy_data['Close'],
    mode='markers',
    name='Buy',
    marker=dict(color='green',size=6)
))

hold_data=ap_data[ap_data['Recommendation']=='Hold']

fig.add_trace(go.Scatter(
    x=hold_data.index,
    y=hold_data['Close'],
    mode='markers',
    name='Hold',
    marker=dict(color='Blue',size=3)
))

fig.update_layout(
    title =  'Trading Recommendation System',
    xaxis_title = 'Date',
    yaxis_title='Price'
)

fig.show()

In [16]:
ap_data.to_csv('../data/appl_day6_trading_decision.csv')